<?php

/**
 * @file
 * Main file of this module. Loads include files and implements general hooks.
 */

module_load_include('inc', 'geoserver', '/geoserver.openlayers');
module_load_include('inc', 'geoserver', '/geoserver.layer');

/**
 * Implements hook_cron().
 * 
 * Access web interface of GeoServer every hour with every active user to keep sessions alive.
 */
function geoserver_cron() {
  if (time() >= variable_get('geoserver_next_execution', 0)) {
    $users = db_query('SELECT uid FROM {sessions} WHERE uid != 0')->fetchAll(PDO::FETCH_COLUMN);
    foreach ($users as $uid) {
      geoserver_get('web/', $uid);
    }
    variable_set('geoserver_next_execution', time() + 3600);
  }
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * Required for OpenLayers integration.
 */
function geoserver_ctools_plugin_api($module, $api) {
  if ($module == 'openlayers') {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function geoserver_ctools_plugin_directory($module, $plugin) {
  if ($module == 'geoserver' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function geoserver_ctools_plugin_type() {
  return array(
    'layer_types' => array()
  );
}

/**
 * Implements hook_user_login().
 */
function geoserver_user_login(&$edit, $account) {

  $url    = parse_url(variable_get('geoserver_url', ''));
  $fields = 'username=' . urlencode($edit['values']['name']) .
            '&password=' . urlencode($edit['values']['pass']) .
            '&_spring_security_remember_me=on';

  $file   = _geoserver_get_cookiefile();
  file_put_contents($file, '');

  $request = curl_init('http://' . $url['host'] . $url['path'] . 'j_spring_security_check');
  curl_setopt($request, CURLOPT_POST, 3);
  curl_setopt($request, CURLOPT_POSTFIELDS, $fields);
  curl_setopt($request, CURLOPT_COOKIEJAR, $file);
  curl_setopt($request, CURLOPT_RETURNTRANSFER, TRUE);
  curl_exec($request);
  curl_close($request);

  // Parse cookie file.
  $cookies = array();
  $lines = file($file);
  foreach ($lines as $line) {
    if ('#' === $line{0}) {
      continue;
    }
    $columns = explode("\t", $line);
    if (isset($columns[5]) && isset($columns[6])) {
      $cookies[$columns[5]] = drupal_substr($columns[6], 0, -1);
    }
  }

  if (isset($cookies['SPRING_SECURITY_REMEMBER_ME_COOKIE']) &&
      $cookies['SPRING_SECURITY_REMEMBER_ME_COOKIE'] != '""') {
    setcookie('JSESSIONID', $cookies['JSESSIONID'], 0, $url['path'], $url['host']);
    setcookie('SPRING_SECURITY_REMEMBER_ME_COOKIE', $cookies['SPRING_SECURITY_REMEMBER_ME_COOKIE'], 0, $url['path'], $url['host']);
  }
  else {
    watchdog('geoserver', 'Could not authenticate %username at %url.',
        array('%username' => urlencode($edit['values']['name']), '%url' => $url), WATCHDOG_ERROR);
  }
}

/**
 * Implements hook_user_login().
 */
function geoserver_user_logout($account) {

  $url = parse_url(variable_get('geoserver_url', ''));

  setcookie('JSESSIONID', '', 1, $url['path'], $url['host']);
  setcookie('SPRING_SECURITY_REMEMBER_ME_COOKIE', '', 1, $url['path'], $url['host']);

  unlink(_geoserver_get_cookiefile());
}

/**
 * Implements hook_node_insert().
 */
function geoserver_node_insert($node) {
  geoserver_truncate($node);
}

/**
 * Implements hook_node_update().
 */
function geoserver_node_update($node) {
  geoserver_truncate($node);
}

/**
 * Implements hook_node_delete().
 */
function geoserver_node_delete($node) {
  geoserver_truncate($node);
}

/**
 * Truncate GeoWebCache after changes to specific node.
 * Requires a cached WMS layer for the content type of the node.
 */
function geoserver_truncate($node) {

  $content_type_settings = variable_get('geoserver_content_type_settings', array());

  if (isset($content_type_settings[$node->type]) && $content_type_settings[$node->type]['gwc']) {
    // Node belongs to a content type with a GeoWebCache layer.
    $workspace = variable_get('geoserver_workspace', '');
    $settings = $content_type_settings[$node->type];
    $field_name = drupal_substr($settings['geometry_column'], 0, -9);
    $field = field_info_field($field_name);

    $geo_set = new PostgisGeometrySet($field['settings']['type'], $field['settings']['srid']);
    $geo_set->fromGeometry($node->{$field_name}[$node->language]);

    if (isset($node->original)) {
      foreach ($node->original->{$field_name}[$node->language] as $geometry) {
        $geo = new PostgisGeometry($field['settings']['type'], $field['settings']['srid']);
        $geo->fromGeometry($geometry);
        $geo_set->add($geo);
      }
    }

    $layer = $workspace . ':' . trim($settings['layer']);
    $srid = explode(':', $settings['gwc_srs']);
    $bbox = preg_split('/[\, ]/', drupal_substr($geo_set->getBox(0.1, $srid[1]), 4, -1));

    if (count($bbox) == 4) {

      $message = '<?xml version="1.0" encoding="UTF-8"?>
                  <seedRequest>
                    <name>' . $layer . '</name>
                    <bounds>
                      <coords>
                        <double>' . $bbox[0] . '</double>
                        <double>' . $bbox[1] . '</double>
                        <double>' . $bbox[2] . '</double>
                        <double>' . $bbox[3] . '</double>
                      </coords>
                    </bounds>
                    <gridSetId>' . $settings['gwc_srs'] . '</gridSetId>
                    <zoomStart>0</zoomStart>
                    <zoomStop>20</zoomStop>
                    <format>image/png</format>
                    <type>truncate</type>
                    <threadCount>1</threadCount>
                  </seedRequest>';

      geoserver_post('/gwc/rest/seed/' . $layer . '.xml', $message);
    }
  }
}

/**
 * Helper function to make a POST request.
 *
 * @param String $url Path relative to GeoServer URL.
 * @param String $content Payload.
 */
function geoserver_post($url, $content) {

  $url = variable_get('geoserver_url', '') . trim($url, '/');

  if (substr($url, -3) == 'xml') {
    $headers = array(
      'Content-Length: ' . drupal_strlen($content),
      'Content-type: text/xml',
    );
  }
  elseif (substr($url, -4) == 'json') {
    $content = json_encode($content);
    $headers = array(
      'Content-type: application/json'
    );
  }
  elseif (substr($url, -3) == 'sld') {
    $headers = array(
      'Content-type: application/vnd.ogc.sld+xml'
    );
  }
  else {
    throw new Exception('Unsupported format.');
  }

  $request = curl_init($url);

  curl_setopt($request, CURLOPT_POST, TRUE);
  curl_setopt($request, CURLOPT_POSTFIELDS, $content);
  curl_setopt($request, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($request, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($request, CURLOPT_COOKIEFILE, _geoserver_get_cookiefile());

  $result = new stdClass();
  $result->data = curl_exec($request);
  $result->code = curl_getinfo($request, CURLINFO_HTTP_CODE);
  curl_close($request);

  if ($result->code === 200) {
    watchdog('geoserver', 'Requested %url.', array('%url' => $url));
  }
  else {
    watchdog('geoserver', 'Requested %url with error %code: %message',
      array('%url' => $url, '%code' => $result->code, '%message' => $result->data), WATCHDOG_ERROR);
  }

  return $result;
}

/**
 * Helper function to make a PUT request.
 *
 * @param String $url Path relative to GeoServer URL.
 * @param String $content Payload.
 */
function geoserver_put($url, $content) {

  $url = variable_get('geoserver_url', '') . trim($url, '/');
  
  if (substr($url, -3) == 'xml') {
    $headers = array(
      'Content-Length: ' . drupal_strlen($content),
      'Content-type: text/xml',
    );
  }
  elseif (substr($url, -4) == 'json') {
    $content = json_encode($content);
    $headers = array(
      'Content-type: application/json'
    );
  }
  elseif (substr($url, -3) == 'sld') {
    $headers = array(
      'Content-type: application/vnd.ogc.sld+xml'
    );
  }
  else {
    throw new Exception('Unsupported format.');
  }
  
  // Create temporary file from payload.
  $file = tmpfile();
  fwrite($file, $content);
  fseek($file, 0);

  $request = curl_init($url);

  curl_setopt($request, CURLOPT_PUT, TRUE);
  curl_setopt($request, CURLOPT_INFILE, $file);
  curl_setopt($request, CURLOPT_INFILESIZE, drupal_strlen($content));
  curl_setopt($request, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($request, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($request, CURLOPT_COOKIEFILE, _geoserver_get_cookiefile());

  $result = new stdClass();
  $result->url  = $url;
  $result->data = curl_exec($request);
  $result->code = curl_getinfo($request, CURLINFO_HTTP_CODE);
  curl_close($request);

  if ($result->code === 200) {
    watchdog('geoserver', 'Requested %url.', array('%url' => $url));
  }
  else {
    watchdog('geoserver', 'Requested %url with error %code: %message',
      array('%url' => $url, '%code' => $result->code, '%message' => $result->data), WATCHDOG_ERROR);
  }

  return $result;
}

/**
 * Helper function to make a GET request.
 *
 * @param String $url Path relative to GeoServer URL.
 */
function geoserver_get($url, $uid = NULL) {

  $url = variable_get('geoserver_url', '') . trim($url, '/');

  $request = curl_init($url);

  curl_setopt($request, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($request, CURLOPT_COOKIEFILE, _geoserver_get_cookiefile($uid));

  $result = new stdClass();
  $result->url = $url;
  $result->data = curl_exec($request);
  $result->code = curl_getinfo($request, CURLINFO_HTTP_CODE);
  curl_close($request);
  
  if (substr($result->url, -4) == 'json' && $result->code == 200) {
    $result->data = json_decode($result->data);
  }

  if ($result->code === 200) {
    watchdog('geoserver', 'Requested %url.', array('%url' => $url));
  }
  else {
    watchdog('geoserver', 'Requested %url with error %code: %message',
      array('%url' => $url, '%code' => $result->code, '%message' => $result->data), WATCHDOG_ERROR);
  }

  return $result;
}

/**
 * Helper function to make a POST request.
 */
function geoserver_admin() {
  $url = variable_get('geoserver_url', '');
  return array('#markup' => '<iframe src="' . $url . '" width="100%" height="2000px" onload="jQuery(\'iframe\').contents().find(\'#header\').hide()"></iframe>');
}

/**
 * Implements hook_menu().
 */
function geoserver_menu() {
  $items = array();

  $items['admin/config/system/geoserver'] = array(
    'title' => 'GeoServer',
    'description' => 'GeoServer settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geoserver_settings_form'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/geoserver'] = array(
    'title' => 'GeoServer',
    'description' => 'GeoServer administration.',
    'page callback' => 'geoserver_admin',
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/structure/types/manage/%node_type/geoserver'] = array(
    'title' => 'GeoServer',
    'description' => 'Publish content type with GeoServer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geoserver_content_type_settings', 4),
    'access callback' => 'geoserver_content_type_settings_access',
    'access arguments' => array(4),
    'type' => MENU_LOCAL_TASK,
    'file' => 'geoserver.admin.inc',
    'weight' => 1,
  );

  return $items;
}

/**
 *  Function to generate the form setting array
 */
function geoserver_settings_form() {
  
  $url        = variable_get('geoserver_url', '');
  $namespace  = variable_get('geoserver_namespace', '');
  $workspace  = variable_get('geoserver_workspace', '');
  $datastore  = variable_get('geoserver_datastore', '');
  $workspaces = array();
  $datastores = array();
  
  if (!empty($url)) {
    
    $result = geoserver_get('rest/workspaces.json');
    if ($result->code == 200) {
      foreach ($result->data->workspaces->workspace as $ws) {
        $workspaces[$ws->name] = $ws->name;
      }
    }
    
    if (!empty($workspace)) {
      
      $result = geoserver_get('rest/namespaces/' . $workspace . '.json');
      if ($result->code == 200) {
        $namespace = $result->data->namespace->uri;
      }
      
      $result = geoserver_get('rest/workspaces/' . $workspace . '/datastores.json');
      if ($result->code == 200) {
        foreach ($result->data->dataStores->dataStore as $ds) {
          $datastores[$ds->name] = $ds->name;
        }
      }
    }
  }

  $form = array(
    'geoserver_url' => array(
      '#type' => 'textfield',
      '#title' => t('URL'),
      '#default_value' => $url,
      '#description' => 'The URL where GeoServer is running. Needs to end with a slash.',
    ),
    'geoserver_workspace' => array(
      '#type' => 'select',
      '#title' => t('Workspace'),
      '#options' => $workspaces,
      '#default_value' => $workspace,
      '#ajax' => array(
        'callback' => 'geoserver_settings_form_workspace_changed',
        'wrapper' => 'geoserver_namespace_datastore'
      ),
    ),
    'geoserver_namespace' => array(
      '#type' => 'textfield',
      '#title' => t('Namespace URI'),
      '#disabled' => TRUE,
      '#default_value' => $namespace,
      '#prefix' => '<div id="geoserver_namespace_datastore">',
    ),
    'geoserver_datastore' => array(
      '#type' => 'select',
      '#title' => t('Datastore'),
      '#options' => $datastores,
      '#default_value' => $datastore,
      '#suffix' => '</div>',
    ),
  );
  return system_settings_form($form);
}

function geoserver_settings_form_workspace_changed($form, $form_state) {
  
  $workspace  = $form['geoserver_workspace']['#value'];
  $namespace  = '';
  $datastores = array();
  
  if (!empty($workspace)) {
      
    $result = geoserver_get('rest/namespaces/' . $workspace . '.json');
    if ($result->code == 200) {
      $namespace = $result->data->namespace->uri;
    }

    $result = geoserver_get('rest/workspaces/' . $workspace . '/datastores.json');
    if ($result->code == 200) {
      foreach ($result->data->dataStores->dataStore as $ds) {
        $datastores[$ds->name] = $ds->name;
      }
    }
  }
  
  $form['geoserver_namespace']['#value'] = $namespace;
  $form['geoserver_datastore']['#options'] = $datastores;
  
  return array($form['geoserver_namespace'], $form['geoserver_datastore']);
}

/**
 * Check if a given entity has geospatial attributes.
 */
function geoserver_content_type_settings_access($entity) {

  $fields = field_info_instances('node', $entity->type);

  foreach ($fields as $field) {
    if ($field['widget']['module'] === 'postgis') {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Get path of file where GeoServer's session cookies are stored.
 *
 * @return string Path of GeoServer's session cookie.
 */
function _geoserver_get_cookiefile($uid = NULL) {
  if (empty($uid)) {
    global $user;
    $uid = $user->uid;
  }
  return file_directory_temp() . '/geoserver_session_user_' . $uid;
}

