<?php

/**
 * @file
 * Main Drupal module file for the GeoServer UI module
 *
 * @ingroup geoserver
 */

/**
 * Implements hook_menu().
 */
function geoserver_ui_menu() {
  $items = array();

  // Core geoserver settings pages.
  $items['admin/structure/geoserver'] = array(
    'title' => 'GeoServer',
    'description' => 'Manage a GeoServer instance.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geoserver_ui_admin_settings_form'),
    'access arguments' => array('administer geoserver'),
    'file' => 'geoserver_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/geoserver/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function geoserver_ui_permission() {
  return array(
    'administer geoserver' => array(
      'title' => t('Administer GeoServer'),
      'description' => t('Configure a GeoServer instance.'),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function geoserver_ui_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}